package br.com.portalRH.PortalRh.model;

public enum Escolaridade {

    FUNDAMENTALCOMPLETO,
    FUNDAMENTALINCOMPLETO,
    MEDIOCOMPLETO,
    MEDIOINCOMPLETO,
    GRADUACAOCOMPLETO,
    GRADUACAOINCOMPLETO,
    POSCOMPLETO,
    POSINCOMPLETO
}
